### ISSUE TITLE
Demo Script

### ISSUE THREAD

**Issue by anas-zafar** [wusize/multiview_pose#2]
Thank you for the amazing work! Do you have a demo script available for qualitative testing? Thanks

**Comment by wusize** [comment]
Hi! Thanks for yor interest in our work. Our code is based on MMPose and the model inherits [DetectAndRegress](https://github.com/open-mmlab/mmpose/blob/reform_multiviewpose/mmpose/models/detectors/multiview_pose.py#L440). You can try using the demo script of [MMPose](https://github.com/open-mmlab/mmpose/blob/reform_multiviewpose/demo/body3d_multiview_detect_and_regress_img_demo.py) to run a demo of our work. You can refer to this [tutorial](https://mmpose.readthedocs.io/en/latest/demo.html#d-multiview-human-pose-estimation-image-demo) on how to use MMPose's demos.
